<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UserSecretsId>dotnet-PhotoRenamer.Cli-26db1b43-1dd8-4f60-9363-bcb9657450b7</UserSecretsId>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cocona" />
    <PackageReference Include="Microsoft.Management.Infrastructure" />
    <PackageReference Include="Microsoft.PowerShell.SDK" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\photo-rename-common\src\PhotoRename.Common\PhotoRename.Common.csproj" />
  </ItemGroup>
</Project>
