using LineToBibleReference.Console.Models;
using LineToBibleReference.Console.Models.Enums;

namespace LineToBibleReference.Console;
internal class Constants
{
    public static readonly List<BibleBook> BibleBooks = new()
    {
        new() { Id = 1, Name = "Genesis", ChaptersLxx = 50, ChaptersHeb = 50, AlternativeNames = new [] { "Ge", "בראשית" } },
        new() { Id = 2, Name = "Exodus", ChaptersLxx = 40, ChaptersHeb = 40, AlternativeNames = new [] { "Ex", "ואלה שמות" } },
        new() { Id = 3, Name = "Leviticus", ChaptersLxx = 27, ChaptersHeb = 27, AlternativeNames = new [] { "Le", "ויקרא" } },
        new() { Id = 4, Name = "Numbers", ChaptersLxx = 36, ChaptersHeb = 36, AlternativeNames = new [] { "Nu", "במדבר" } },
        new() { Id = 5, Name = "Deuteronomy", ChaptersLxx = 34, ChaptersHeb = 34, AlternativeNames = new [] { "Dt", "אלה הדברים" } },
        new() { Id = 6, Name = "Joshua", ChaptersLxx = 24, ChaptersHeb = 24, AlternativeNames = new [] { "Jos", "יהושע" } },
        new() { Id = 7, Name = "Judges", ChaptersLxx = 21, ChaptersHeb = 21, AlternativeNames = new [] { "Jdg", "שפטים" } },
        new() { Id = 8, Name = "Ruth", ChaptersLxx = 4, ChaptersHeb = 4, AlternativeNames = new [] { "Ru", "רות" } },
        new() { Id = 9, Name = "1 Samuel", ChaptersLxx = 31, ChaptersHeb = 31, AlternativeNames = new [] { "1 Sa", "שמואל א" } },
        new() { Id = 10, Name = "2 Samuel", ChaptersLxx = 24, ChaptersHeb = 24, AlternativeNames = new [] { "2 Sa", "שמואל ב" } },
        new() { Id = 11, Name = "1 Kings", ChaptersLxx = 22, ChaptersHeb = 22, AlternativeNames = new [] { "1 Ki", "מלכים א" } },
        new() { Id = 12, Name = "2 Kings", ChaptersLxx = 25, ChaptersHeb = 25, AlternativeNames = new [] { "2 Ki", "מלכים ב" } },
        new() { Id = 13, Name = "1 Chronicles", ChaptersLxx = 29, ChaptersHeb = 29, AlternativeNames = new [] { "1 Ch", "דברי הימים א" } },
        new() { Id = 14, Name = "2 Chronicles", ChaptersLxx = 36, ChaptersHeb = 36, AlternativeNames = new [] { "2 Ch", "דברי הימים ב" } },
        new() { Id = 15, Name = "Ezra", ChaptersLxx = 10, ChaptersHeb = 10, AlternativeNames = new [] { "Ezr", "עזרא" } },
        new() { Id = 16, Name = "Nehemiah", ChaptersLxx = 13, ChaptersHeb = 13, AlternativeNames = new [] { "Ne", "נחמיה" } },
        new() { Id = 17, Name = "Esther", ChaptersLxx = 10, ChaptersHeb = 10, AlternativeNames = new [] { "Es", "אסתר" } },
        new() { Id = 18, Name = "Job", ChaptersLxx = 42, ChaptersHeb = 42, AlternativeNames = new [] { "Job", "איוב" } },
        new() { Id = 19, Name = "Psalms", ChaptersLxx = 150, ChaptersHeb = 150, AlternativeNames = new [] { "Ps", "Psalm", "תהלים" } },
        new() { Id = 20, Name = "Proverbs", ChaptersLxx = 31, ChaptersHeb = 31, AlternativeNames = new [] { "Pr", "משלי" } },
        new() { Id = 21, Name = "Ecclesiastes", ChaptersLxx = 12, ChaptersHeb = 12, AlternativeNames = new [] { "Ec", "קהלת" } },
        new() { Id = 22, Name = "Song of Songs", ChaptersLxx = 8, ChaptersHeb = 8, AlternativeNames = new [] { "So", "Song of Solomon", "שיר השירים" } },
        new() { Id = 23, Name = "Isaiah", ChaptersLxx = 66, ChaptersHeb = 66, AlternativeNames = new [] { "Is", "ישעיה" } },
        new() { Id = 24, Name = "Jeremiah", ChaptersLxx = 52, ChaptersHeb = 52, AlternativeNames = new [] { "Je", "ירמיה" } },
        new() { Id = 25, Name = "Lamentations", ChaptersLxx = 5, ChaptersHeb = 5, AlternativeNames = new [] { "La", "איכה" } },
        new() { Id = 26, Name = "Ezekiel", ChaptersLxx = 48, ChaptersHeb = 48, AlternativeNames = new [] { "Eze", "יחזקאל" } },
        new() { Id = 27, Name = "Daniel", ChaptersLxx = 12, ChaptersHeb = 12, AlternativeNames = new [] { "Da", "דניאל" } },
        new() { Id = 28, Name = "Hosea", ChaptersLxx = 14, ChaptersHeb = 14, AlternativeNames = new [] { "Ho", "הושע" } },
        new() { Id = 29, Name = "Joel", ChaptersLxx = 3, ChaptersHeb = 4, AlternativeNames = new [] { "Joe", "יואל" } },
        new() { Id = 30, Name = "Amos", ChaptersLxx = 9, ChaptersHeb = 9, AlternativeNames = new [] { "Am", "עמוס" } },
        new() { Id = 31, Name = "Obadiah", ChaptersLxx = 1, ChaptersHeb = 1, AlternativeNames = new [] { "Ob", "עבדיה" } },
        new() { Id = 32, Name = "Jonah", ChaptersLxx = 4, ChaptersHeb = 4, AlternativeNames = new [] { "Jon", "יונה" } },
        new() { Id = 33, Name = "Micah", ChaptersLxx = 7, ChaptersHeb = 7, AlternativeNames = new [] { "Mic", "מיכה" } },
        new() { Id = 34, Name = "Nahum", ChaptersLxx = 3, ChaptersHeb = 3, AlternativeNames = new [] { "Na", "נחום" } },
        new() { Id = 35, Name = "Habakkuk", ChaptersLxx = 3, ChaptersHeb = 3, AlternativeNames = new [] { "Hab", "חבקוק" } },
        new() { Id = 36, Name = "Zephaniah", ChaptersLxx = 3, ChaptersHeb = 3, AlternativeNames = new [] { "Zep", "צפניה" } },
        new() { Id = 37, Name = "Haggai", ChaptersLxx = 2, ChaptersHeb = 2, AlternativeNames = new [] { "Hag", "חגי" } },
        new() { Id = 38, Name = "Zechariah", ChaptersLxx = 14, ChaptersHeb = 14, AlternativeNames = new [] { "Zec", "זכריה" } },
        new() { Id = 39, Name = "Malachi", ChaptersLxx = 4, ChaptersHeb = 3, AlternativeNames = new [] { "Mal", "מלאכי" } },
        new() { Id = 40, Name = "Matthew", ChaptersLxx = 28, ChaptersHeb = 28, AlternativeNames = new [] { "Mt" } },
        new() { Id = 41, Name = "Mark", ChaptersLxx = 16, ChaptersHeb = 16, AlternativeNames = new [] { "Mk" } },
        new() { Id = 42, Name = "Luke", ChaptersLxx = 24, ChaptersHeb = 24, AlternativeNames = new [] { "Lk" } },
        new() { Id = 43, Name = "John", ChaptersLxx = 21, ChaptersHeb = 21, AlternativeNames = new [] { "Jn" } },
        new() { Id = 44, Name = "Acts", ChaptersLxx = 28, ChaptersHeb = 28, AlternativeNames = new [] { "Ac" } },
        new() { Id = 45, Name = "Romans", ChaptersLxx = 16, ChaptersHeb = 16, AlternativeNames = new [] { "Ro" } },
        new() { Id = 46, Name = "1 Corinthians", ChaptersLxx = 16, ChaptersHeb = 16, AlternativeNames = new [] { "1 Co" } },
        new() { Id = 47, Name = "2 Corinthians", ChaptersLxx = 13, ChaptersHeb = 13, AlternativeNames = new [] { "2 Co" } },
        new() { Id = 48, Name = "Galatians", ChaptersLxx = 6, ChaptersHeb = 6, AlternativeNames = new [] { "Ga" } },
        new() { Id = 49, Name = "Ephesians", ChaptersLxx = 6, ChaptersHeb = 6, AlternativeNames = new [] { "Eph" } },
        new() { Id = 50, Name = "Philippians", ChaptersLxx = 4, ChaptersHeb = 4, AlternativeNames = new [] { "Php" } },
        new() { Id = 51, Name = "Colossians", ChaptersLxx = 4, ChaptersHeb = 4, AlternativeNames = new [] { "Col" } },
        new() { Id = 52, Name = "1 Thessalonians", ChaptersLxx = 5, ChaptersHeb = 5, AlternativeNames = new [] { "1 Th" } },
        new() { Id = 53, Name = "2 Thessalonians", ChaptersLxx = 3, ChaptersHeb = 3, AlternativeNames = new [] { "2 Th" } },
        new() { Id = 54, Name = "1 Timothy", ChaptersLxx = 6, ChaptersHeb = 6, AlternativeNames = new [] { "1 Ti" } },
        new() { Id = 55, Name = "2 Timothy", ChaptersLxx = 4, ChaptersHeb = 4, AlternativeNames = new [] { "2 Ti" } },
        new() { Id = 56, Name = "Titus", ChaptersLxx = 3, ChaptersHeb = 3, AlternativeNames = new [] { "Tt" } },
        new() { Id = 57, Name = "Philemon", ChaptersLxx = 1, ChaptersHeb = 1, AlternativeNames = new [] { "Phm" } },
        new() { Id = 58, Name = "Hebrews", ChaptersLxx = 13, ChaptersHeb = 13, AlternativeNames = new [] { "Heb" } },
        new() { Id = 59, Name = "James", ChaptersLxx = 5, ChaptersHeb = 5, AlternativeNames = new [] { "Jas" } },
        new() { Id = 60, Name = "1 Peter", ChaptersLxx = 5, ChaptersHeb = 5, AlternativeNames = new [] { "1 Pe" } },
        new() { Id = 61, Name = "2 Peter", ChaptersLxx = 3, ChaptersHeb = 3, AlternativeNames = new [] { "2 Pe" } },
        new() { Id = 62, Name = "1 John", ChaptersLxx = 5, ChaptersHeb = 5, AlternativeNames = new [] { "1 Jn" } },
        new() { Id = 63, Name = "2 John", ChaptersLxx = 1, ChaptersHeb = 1, AlternativeNames = new [] { "2 Jn" } },
        new() { Id = 64, Name = "3 John", ChaptersLxx = 1, ChaptersHeb = 1, AlternativeNames = new [] { "3 Jn" } },
        new() { Id = 65, Name = "Jude", ChaptersLxx = 1, ChaptersHeb = 1, AlternativeNames = new [] { "Jud" } },
        new() { Id = 66, Name = "Revelation", ChaptersLxx = 22, ChaptersHeb = 22, AlternativeNames = new [] { "Re" } }
    };

    public static readonly List<CharacterStatsItem> GermanCharacterList = new()
    {
        new('I', 73, 5308, CharacterTypes.CapitalLetter | CharacterTypes.Vowel),
        new('m', 109, 79855),
        new(' ', 32, 727751, CharacterTypes.Space),
        new('A', 65, 9609, CharacterTypes.CapitalLetter | CharacterTypes.Vowel),
        new('n', 110, 361799),
        new('f', 102, 31935),
        new('a', 97, 177972, CharacterTypes.Vowel),
        new('g', 103, 79291),
        new('s', 115, 203943),
        new('c', 99, 86591),
        new('h', 104, 160298),
        new('u', 117, 136043),
        new('G', 71, 16112),
        new('o', 111, 72929),
        new('t', 116, 171577),
        new('d', 100, 219705),
        new('i', 105, 251257),
        new('e', 101, 562172),
        new('H', 72, 21406),
        new('l', 108, 90631),
        new('E', 69, 8937),
        new('r', 114, 246937),
        new('.', 46, 25997, CharacterTypes.Punctuation),
        new('U', 85, 14750),
        new('w', 119, 45757),
        new('ü', 252, 18687),
        new(',', 44, 67852, CharacterTypes.Punctuation),
        new('F', 70, 7702),
        new('b', 98, 53372),
        new('T', 84, 7512),
        new(';', 59, 12596, CharacterTypes.Punctuation),
        new('W', 87, 11287),
        new('p', 112, 16418),
        new(':', 58, 10064, CharacterTypes.Punctuation),
        new('L', 76, 7025),
        new('!', 33, 3881, CharacterTypes.Punctuation),
        new('v', 118, 21156),
        new('N', 78, 4728),
        new('M', 77, 9994),
        new('z', 122, 30504),
        new('O', 79, 2025),
        new('k', 107, 23231),
        new('S', 83, 22661),
        new('D', 68, 10477),
        new('K', 75, 9898),
        new('ä', 228, 12067),
        new('B', 66, 9673),
        new('Z', 90, 4054),
        new('J', 74, 8254),
        new('ß', 223, 4870),
        new('–', 8211, 1092, CharacterTypes.Punctuation),
        new('V', 86, 6921),
        new('ö', 246, 12785),
        new('j', 106, 4889),
        new('P', 80, 4192),
        new('y', 121, 1393),
        new('x', 120, 41),
        new('R', 82, 3762),
        new('?', 63, 2922, CharacterTypes.Punctuation),
        new('C', 67, 819),
        new('1', 49, 328),
        new('3', 51, 198),
        new('0', 48, 1619),
        new('8', 56, 81),
        new('9', 57, 46),
        new('5', 53, 225),
        new('7', 55, 145),
        new('2', 50, 370),
        new('’', 8217, 29, CharacterTypes.Quotation),
        new('4', 52, 169),
        new('6', 54, 146),
        new('Q', 81, 93),
        new('-', 45, 829, CharacterTypes.Punctuation),
        new('Ä', 196, 1043),
        new('Ü', 220, 625),
        new('q', 113, 80),
        new('„', 8222, 548, CharacterTypes.Quotation),
        new('“', 8220, 550, CharacterTypes.Quotation),
        new('Ö', 214, 273),
        new('Y', 89, 12),
        new('…', 8230, 1, CharacterTypes.Punctuation),
        new('*', 42, 7),
        new('‘', 8216, 5, CharacterTypes.Quotation),
        new('[', 91, 3, CharacterTypes.Parentheses),
        new('"', 34, 2, CharacterTypes.Quotation),
        new(']', 93, 3, CharacterTypes.Parentheses),
    };

    public static readonly List<CharacterStatsItem> HebrewCharacterList = new()
    {
        new('ב', 1489, 65216),
        new('ְ', 1456, 150413) { Description = "Sheva" },
        new('ּ', 1468, 170769) { Description = "Dagesh, Mappiq, Shuruk" },
        new('ר', 1512, 68064),
        new('ֵ', 1461, 59026, CharacterTypes.Vowel) { Description = "Tsere" },
        new('א', 1488, 95685),
        new('ש', 1513, 58198),
        new('ִ', 1460, 109066, CharacterTypes.Vowel) { Description = "Hiriq" },
        new('ׁ', 1473, 46069) { Description = "Shin" },
        new('֖', 1430, 37024, CharacterTypes.Accent) { Description = "Tifcha" },
        new('י', 1497, 137869),
        new('ת', 1514, 63206),
        new(' ', 32, 242875, CharacterTypes.Space),
        new('ָ', 1464, 151807, CharacterTypes.Vowel) { Description = "Kamatz" },
        new('֣', 1443, 41180, CharacterTypes.Accent) { Description = "Munach" },
        new('ֱ', 1457, 4473, CharacterTypes.Vowel) { Description = "Hataf Segol" },
        new('ל', 1500, 88302),
        new('ֹ', 1465, 73668, CharacterTypes.Vowel) { Description = "Holam" },
        new('ה', 1492, 101962),
        new('֑', 1425, 21479, CharacterTypes.Accent) { Description = "Etnachta" },
        new('ם', 1501, 41291, CharacterTypes.FinalOnly),
        new('֥', 1445, 33074, CharacterTypes.Accent) { Description = "Mercha" },
        new('ַ', 1463, 117290, CharacterTypes.Vowel) { Description = "Patach" },
        new('מ', 1502, 57638),
        new('ו', 1493, 129607),
        new('ֽ', 1469, 41095, CharacterTypes.Punctuation) { Description = "Meteg" },
        new('ֶ', 1462, 75246, CharacterTypes.Accent) { Description = "Segol" },
        new('ץ', 1509, 3288, CharacterTypes.FinalOnly),
        new('׃', 1475, 23213, CharacterTypes.Punctuation) { Description = "Sof Passuk" },
        new('֗', 1431, 12747, CharacterTypes.Accent) { Description = "Rivia" },
        new('֙', 1433, 24333, CharacterTypes.Accent) { Description = "Pashta" },
        new('֔', 1428, 25455, CharacterTypes.Accent) { Description = "Zakef katan" },
        new('ח', 1495, 27598),
        new('ך', 1498, 14002, CharacterTypes.FinalOnly),
        new('ע', 1506, 44811),
        new('־', 1470, 42594, CharacterTypes.Punctuation) { Description = "Maqaf" },
        new('פ', 1508, 16912),
        new('נ', 1504, 39852),
        new('֧', 1447, 3262, CharacterTypes.Accent) { Description = "Darga" },
        new('֛', 1435, 7822, CharacterTypes.Accent) { Description = "Tevir" },
        new('כ', 1499, 33466),
        new('ט', 1496, 6310),
        new('ד', 1491, 32371),
        new('ן', 1503, 15241, CharacterTypes.FinalOnly),
        new('ק', 1511, 16278),
        new('֨', 1448, 7461, CharacterTypes.Accent) { Description = "Kadma" },
        new('֤', 1444, 12544, CharacterTypes.Accent) { Description = "Mahpach" },
        new('׀', 1472, 2267, CharacterTypes.Punctuation) { Description = "" },
        new('ׂ', 1474, 12085) { Description = "Shin" },
        new('֮', 1454, 1236, CharacterTypes.Accent) { Description = "Zarka" },
        new('֒', 1426, 953, CharacterTypes.Accent) { Description = "Segol (trope)" },
        new('ֲ', 1458, 25590, CharacterTypes.Vowel) { Description = "Patach" },
        new('֜', 1436, 4149, CharacterTypes.Accent) { Description = "Geresh" },
        new('֚', 1434, 1174, CharacterTypes.Accent) { Description = "Yetiv" },
        new('ז', 1494, 9099),
        new('֞', 1438, 1720, CharacterTypes.Accent) { Description = "Gershayim" },
        new('צ', 1510, 11689),
        new('֠', 1440, 1196, CharacterTypes.Accent) { Description = "Telisha" },
        new('֕', 1429, 1649, CharacterTypes.Accent) { Description = "Zakef gadol" },
        new('ג', 1490, 10080),
        new('ף', 1507, 2554, CharacterTypes.FinalOnly),
        new('֡', 1441, 947, CharacterTypes.Accent) { Description = "Pazer" },
        new('֩', 1449, 1868, CharacterTypes.Accent) { Description = "Telisha" },
        new('ֻ', 1467, 4369, CharacterTypes.Vowel) { Description = "Kubutz or Shuruk" },
        new('ס', 1505, 9615),
        new('ֳ', 1459, 629, CharacterTypes.Vowel) { Description = "Kamatz" },
        new('ֺ', 1466, 419, CharacterTypes.Vowel) { Description = "Holam" },
        new('ׄ', 1476, 53, CharacterTypes.Accent) { Description = "" },
        new('֓', 1427, 46, CharacterTypes.Accent) { Description = "Shalshelet" },
        new('֦', 1446, 14, CharacterTypes.Accent) { Description = "Mercha kefula" },
        new('ֿ', 1471, 12, CharacterTypes.Accent) { Description = "Rafe" },
        new('֝', 1437, 2946, CharacterTypes.Accent) { Description = "" },
        new('׆', 1478, 9),
        new('֪', 1450, 250, CharacterTypes.Accent) { Description = "Yerach ben yomo or Galgal" },
        new('֟', 1439, 16, CharacterTypes.Accent) { Description = "Karne parah" },
        new('֘', 1432, 199, CharacterTypes.Accent) { Description = "Tsinnorit" },
        new('֫', 1451, 407, CharacterTypes.Accent) { Description = "Ole" },
        new('֭', 1453, 2609, CharacterTypes.Accent) { Description = "" },
        new('֬', 1452, 182, CharacterTypes.Accent) { Description = "Illuy" },
        new('ׅ', 1477, 3, CharacterTypes.Accent) { Description = "" },
    };


    public static readonly List<CharacterStatsItem> GreekCharacterList = new()
    {
        new('Β', 914, 152, 'β', CharacterTypes.CapitalLetter),
        new('ί', 943, 10041, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('β', 946, 3368),
        new('λ', 955, 18250),
        new('ο', 959, 45184, CharacterTypes.Vowel),
        new('ς', 962, 27086, 'σ', CharacterTypes.FinalOnly),
        new(' ', 32, 129756, CharacterTypes.Space),
        new('γ', 947, 10984) { Description = "Gamma" },
        new('ε', 949, 38363, CharacterTypes.Vowel),
        new('ν', 957, 56163),
        new('έ', 941, 8515, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('σ', 963, 24139),
        new('ω', 969, 7826, CharacterTypes.Vowel),
        new('Ἰ', 7992, 1796, 'ι', CharacterTypes.Vowel | CharacterTypes.CapitalLetter),
        new('η', 951, 9067, CharacterTypes.Vowel),
        new('ῦ', 8166, 8776, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('χ', 967, 4741),
        new('ρ', 961, 22874),
        new('ι', 953, 26130, CharacterTypes.Vowel),
        new('τ', 964, 50629),
        new('υ', 965, 10646, CharacterTypes.Vowel),
        new('ἱ', 7985, 1912, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Δ', 916, 259, 'δ', CharacterTypes.CapitalLetter),
        new('α', 945, 51912, CharacterTypes.Vowel),
        new('ὶ', 8054, 11743, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('δ', 948, 12497),
        new('Ἀ', 7944, 493, 'α', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ά', 940, 6878, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('μ', 956, 19263),
        new('.', 46, 5323, CharacterTypes.Punctuation),
        new('ὰ', 8048, 4907, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἐ', 7952, 12112, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὸ', 8056, 7668, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('κ', 954, 23204),
        new(',', 44, 8986, CharacterTypes.Punctuation),
        new('ὲ', 8050, 3432, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ώ', 974, 2022, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὼ', 8060, 1006, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ύ', 973, 4823, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὺ', 8058, 2019, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἀ', 7936, 7271, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('φ', 966, 3821),
        new('ὐ', 8016, 8597, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Φ', 934, 203, 'φ', CharacterTypes.CapitalLetter),
        new('Ζ', 918, 40, 'ζ', CharacterTypes.CapitalLetter),
        new('ῆ', 8134, 3258, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Θ', 920, 67, 'θ', CharacterTypes.CapitalLetter),
        new('Ἑ', 7961, 59, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ν', 925, 106, 'ν', CharacterTypes.CapitalLetter),
        new('Σ', 931, 420, 'σ', CharacterTypes.CapitalLetter),
        new('ό', 972, 6223, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ῥ', 8172, 53, 'ρ', CharacterTypes.CapitalLetter),
        new('ὴ', 8052, 3831, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('θ', 952, 10699),
        new('ῶ', 8182, 5253, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ο', 927, 295, 'ο', CharacterTypes.Vowel | CharacterTypes.CapitalLetter),
        new('Ὀ', 8008, 20, 'ο', CharacterTypes.Vowel | CharacterTypes.CapitalLetter),
        new('ζ', 950, 1530),
        new('Μ', 924, 421, 'μ', CharacterTypes.CapitalLetter),
        new('π', 960, 20842),
        new('ή', 942, 3615, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἐ', 7960, 364, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ἄ', 7940, 1119, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ξ', 958, 2224),
        new('ἧ', 7975, 52, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὁ', 8001, 3090, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Π', 928, 693, 'π', CharacterTypes.CapitalLetter),
        new('ᾶ', 8118, 1470, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὖ', 8022, 536, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἕ', 7957, 398, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Τ', 932, 471, 'τ', CharacterTypes.CapitalLetter),
        new('ἡ', 7969, 2338, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὕ', 8021, 421, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἦ', 7974, 599, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ῷ', 8183, 2761, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἢ', 7970, 333, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ῖ', 8150, 5624, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὑ', 8017, 2929, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἔ', 7956, 2763, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ἁ', 7937, 515, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὢ', 8034, 39, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ᾳ', 8115, 585, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἰ', 7984, 4120, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ʼ', 700, 1224, CharacterTypes.Punctuation),
        new('ὄ', 8004, 517, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('·', 183, 4258, CharacterTypes.Punctuation),
        new('ῇ', 8135, 1454, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὅ', 8005, 2008, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἵ', 7989, 825, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ῥ', 8165, 178, 'ρ', CharacterTypes.Accent),
        new('ὡ', 8033, 533, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὗ', 8023, 456, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἡ', 7977, 94, 'η', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ῴ', 8180, 87, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἱ', 7993, 70, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new(';', 59, 967, CharacterTypes.Punctuation),
        new('ἴ', 7988, 643, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἤ', 7972, 413, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἶ', 7990, 1385, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Κ', 922, 698, 'κ', CharacterTypes.CapitalLetter),
        new('ἠ', 7968, 352, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ψ', 968, 944),
        new('ὃ', 8003, 553, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Α', 913, 69, 'α', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ἂ', 7938, 174, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὀ', 8000, 566, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ῳ', 8179, 1131, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Γ', 915, 154, 'γ', CharacterTypes.CapitalLetter),
        new('Ἠ', 7976, 66, 'η', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ΐ', 912, 56, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ῃ', 8131, 1023, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἑ', 7953, 770, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ἅ', 7941, 178, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἄ', 7948, 101, 'α', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ᾧ', 8103, 118, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ε', 917, 183, 'ε', CharacterTypes.Vowel | CharacterTypes.CapitalLetter),
        new('Ὕ', 8029, 11, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ᾷ', 8119, 140, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ὑ', 8025, 48, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ἓ', 7955, 59, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ὃ', 8011, 22, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ὒ', 8018, 4, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὔ', 8020, 181, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἥ', 7973, 129, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἔ', 7964, 106, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ὅ', 8013, 57, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ὥ', 8037, 225, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ᾖ', 8086, 44, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὧ', 8039, 139, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ὁ', 8009, 122, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent| CharacterTypes.CapitalLetter),
        new('ῄ', 8132, 39, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('—', 8212, 93, CharacterTypes.Punctuation),
        new('ᾠ', 8096, 15, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ϋ', 971, 83, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἷ', 7991, 212, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἆ', 7942, 16, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἁ', 7945, 30, 'α', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ἤ', 7980, 15, 'η', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ἣ', 7971, 99, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ἃ', 7939, 111, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὦ', 8038, 41, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Η', 919, 2, 'η', CharacterTypes.Vowel | CharacterTypes.CapitalLetter),
        new('ὠ', 8032, 56, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Χ', 935, 490, 'χ', CharacterTypes.CapitalLetter),
        new('ϊ', 970, 69, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ᾅ', 8069, 10, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ΰ', 944, 12, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ᾑ', 8081, 1, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἢ', 7978, 6, 'η', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ὡ', 8041, 34, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ὦ', 8046, 12, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ἵ', 7997, 2, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ὤ', 8036, 43, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἕ', 7965, 27, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Λ', 923, 110, 'λ', CharacterTypes.CapitalLetter),
        new('ῒ', 8146, 15, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ὄ', 8012, 14, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ῢ', 8162, 1, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὓ', 8019, 52, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἅ', 7949, 15, 'α', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ὧ', 8047, 3, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ᾔ', 8084, 35, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ᾗ', 8087, 37, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ὥ', 8045, 7, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ἥ', 7981, 3, 'η', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ἦ', 7982, 25, 'η', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ᾐ', 8080, 14, 'η', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ἴ', 7996, 19, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('(', 40, 25, CharacterTypes.Parentheses),
        new('Υ', 933, 9, CharacterTypes.Vowel | CharacterTypes.CapitalLetter),
        new(')', 41, 25, CharacterTypes.Parentheses),
        new('ἳ', 7987, 35, 'ι', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('ὂ', 8002, 1, 'ο', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ρ', 929, 2, 'ρ', CharacterTypes.CapitalLetter),
        new('⟦', 10214, 3, CharacterTypes.Parentheses),
        new('⟧', 10215, 3, CharacterTypes.Parentheses),
        new('Ψ', 936, 2),
        new('Ἓ', 7963, 3, 'ε', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('[', 91, 6),
        new(']', 93, 6),
        new('Ἆ', 7950, 6, 'α', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ἃ', 7947, 3, 'α', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('ᾴ', 8116, 1, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ξ', 926, 1, 'ξ', CharacterTypes.CapitalLetter),
        new('ᾄ', 8068, 5, 'α', CharacterTypes.Vowel | CharacterTypes.Accent),
        new('Ὤ', 8044, 1, 'ω', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
        new('Ὗ', 8031, 1, 'υ', CharacterTypes.Vowel | CharacterTypes.Accent | CharacterTypes.CapitalLetter),
    };

}
