<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>dotnet-PhotoTimeStampShifter.Cli-650A2EE0-30DD-49F1-B47E-627B4F24AEB1</UserSecretsId>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Cocona" />
    <PackageReference Include="Microsoft.Management.Infrastructure" />
    <PackageReference Include="Microsoft.PowerShell.SDK" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\photo-rename-common\src\PhotoRename.Common\PhotoRename.Common.csproj" />
  </ItemGroup>

</Project>
